### PR TITLE
wip attempt at circleci setup

### PR DESCRIPTION
**Pull request by sglyon**

### CODE REVIEW

**Comment by sglyon** [comment]
@nicolaskruchten see this PR here

I've never used circleci before, so this was my best attempt at doing the Julia think based on the python template. 

Not sure what magic incantations we need to do to get circleci to track this repo and run the job. Any ideas?

**Comment by nicolaskruchten** [comment]
Circle is running! https://app.circleci.com/pipelines/github/plotly/plotlyjs.jl-docs/12/workflows/b1605e74-3ad8-4f6d-9344-53bf66b4f01d/jobs/13

let me wire up the statuses here and get the SSH key hooked in so you can push the output

**Comment by nicolaskruchten** [comment]
I'm not actually sure how to get the status updates... maybe the config needs to land on master first?

Are you able to access this URL btw? https://app.circleci.com/pipelines/github/plotly/plotlyjs.jl-docs

**Comment by nicolaskruchten** [comment]
OK well I fixed the SSH key issue and I reran your build and it failed further down... you can now carry on with this PR. I think the next time you commit you'll get the little statuses that appear at the bottom.

**Comment by nicolaskruchten** [comment]
Hm, still no little statuses here :( I'll try to find time to look into why!

**Comment by sglyon** [comment]
I do have access to the circle ci page though -- looks like the build passed :clap:!

**Pull request merged**
